create schema auth;
create schema private;
create role anon;
create role authenticated;
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create function private.is_sa() returns boolean language sql stable as $$ select current_setting('test.role',true)='sa' $$;
create function private.is_ctrl() returns boolean language sql stable as $$ select current_setting('test.role',true) in ('sa','ctrl') $$;
create function private.has_menu(text) returns boolean language sql stable as $$ select current_setting('test.role',true) in ('sa','ctrl','reader') $$;
create function private.bump_version() returns trigger language plpgsql as $$begin update public.data_versions set updated_at=clock_timestamp() where key=tg_argv[0];return null;end$$;
create table public.profiles(id uuid primary key);
insert into public.profiles values('00000000-0000-0000-0000-000000000001');
select set_config('test.uid','00000000-0000-0000-0000-000000000001',false);
select set_config('test.role','sa',false);
create table public.data_versions(key text primary key,updated_at timestamptz default now());
create table public.ar_targets(month text,invoice_no text,target numeric,marketing text,collection_name text,business_partner text,due_date date,branch text,no_sj text,primary key(month,invoice_no));
create table public.ar_invoices(invoice_no text,marketing text,collection_name text,business_partner text,due_date date,no_sj text);
create table public.ar_aging_snapshots(id bigint generated always as identity primary key,month text unique,as_of date,file_name text,row_count int,total_open numeric,created_at timestamptz default now());
create table public.ar_aging_lines(snapshot_id bigint references public.ar_aging_snapshots(id) on delete cascade,line_no int,payment_group text,limit_group text,marketing text,collection_name text,sales_name text,bp_key text,business_partner text,tax_name text,invoice_no text,invoice_date date,due_date date,open_amt numeric,cur_0_30 numeric,cur_31_60 numeric,due_1_7 numeric,due_8_30 numeric,due_31_60 numeric,due_61_90 numeric,due_90 numeric,days int,branch text,follow_up text,no_po text,no_sj text,area text);
create table public.erp_payments(invoice_no text,payment_date date,amount numeric);
create table public.notes(id bigint,invoice_no text,kategori text);
create table public.payment_promises(id bigint,invoice_no text,promise_date date);
create table public.app_settings(key text primary key,value jsonb,updated_at timestamptz default now(),updated_by uuid);
create table public.import_log(module text,kind text,file_name text,months text[],rows int,user_id uuid,file_sha256 text);
create table public.m10_aging(invoice_no text);
create table private.upload_batches(id uuid primary key,kind text,file_name text,sha256 text,meta jsonb);
create table private.upload_rows(batch uuid references private.upload_batches(id) on delete cascade,seq int,data jsonb);
create function private.take_batch(p uuid,k text) returns private.upload_batches language sql as $$select b from private.upload_batches b where id=p and kind=k$$;
create function private.m10_append_from_aging() returns integer language sql as $$select 0$$;
